#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 22 09:37:58 2019

@author: Will
"""

if type(varA)==str or type(varB)==str:
    print ("string involved")
elif varA>varB:
     print ("bigger")
elif varA==varB:
     print ("equal")
else:
     print ("smaller")